### ISSUE TITLE
Bad locale resolution based on POSIX variables

### ISSUE THREAD

**Issue by jvdm** [sindresorhus/os-locale#13]
If the user is just looking for a locale to provide translated messages this module will return a reasonable locale.

But -- I know that's not very common -- the user may want to select a different locale for each [locale category](https://www.gnu.org/software/gettext/manual/html_node/Aspects.html#Aspects). If he does that using POSIX variables (for example, a user using `LC_MESSAGES=en_US` and `LC_MONETARY=en_GB`) he could see money information in the wrong format if using `os-locale`.

Also, the locale resolution based on environment variables and `locale` stdout is selecting variables in the wrong order (just like [yargs](https://github.com/bcoe/yargs/pull/250) is doing).

IMHO, a good strategy is following [`gettext`](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html) for POSIX environments.

**Comment by sindresorhus** [comment]
> the user may want to select a different locale for each locale category

I considered that when creating this module, but I didn't have any use for it then, so I went with the most common use-case. Happy to reconsider though, if there's demand for it.

> Also, the locale resolution based on environment variables and locale stdout is selecting variables in the wrong order (just like yargs is doing).

I researched extensively to end up with the current order, but I don't remember why now... Happy to switch to the `gettext` order.

**Comment by jvdm** [comment]
> > the user may want to select a different locale for each locale category

> I considered that when creating this module, but I didn't have any
> use for it then, so I went with the most common use-case. Happy to
> reconsider though, if there's demand for it.

I don't have immediate use for retrieving different locales
categories.

But I think it should be mentioned in the README so users will know to
not trust the locale returned for other activities different from
translating messages.

> > Also, the locale resolution based on environment variables and
> > locale stdout is selecting variables in the wrong order (just like
> > yargs is doing).

> I researched extensively to end up with the current order, but I
> don't remember why now... Happy to switch to the gettext order.

The handling of those environment variables for the purpose of setting
locale information is a POSIX standard, see `setlocal(3)` man page.

**Comment by sindresorhus** [comment]
Fixed by #15.
