### ISSUE TITLE
Can not get Locale in Mac with locale zh_ch.utf8

### ISSUE THREAD

**Issue by rodney-vin** [sindresorhus/os-locale#18]
It seems a NodeJS process issue.
1, execute "locale" in mac terminal:
locale
LANG="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_ALL=

2, call locale via process.childProcess.execFileSync
var childProcess = require('child_process');
var execFileSync = childProcess.execFileSync;
var ret = execFileSync('locale', {encoding: 'utf8'});
console.log(ret);

Notice the difference of output:
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

**Comment by SamVerschueren** [comment]
What node version are you using? Works perfect for me.

**Comment by rodney-vin** [comment]
node-v0.12.7-darwin-x64  and OSX 10.11.3

trying to update node to latest LTS version.

**Comment by rodney-vin** [comment]
/*
        try {
            res = parseLocale(execFileSync('locale', {encoding: 'utf8'}));
        } catch (err) {}        
        */

        if (!res && process.platform === 'darwin') {
            try {
                cache = execFileSync('defaults', ['read', '-g', 'AppleLocale'], {encoding: 'utf8'}).trim() || fallback();
                return cache;
            } catch (err) {
                return fallback();
            }
        }

**Comment by rodney-vin** [comment]
execFileSync('defaults', ['read', '-g', 'AppleLocale'], this works fine.

so adjust the order, execute "defaults" on darwin will fix this issue.

**Comment by sindresorhus** [comment]
I can reproduce when I comment out my `LANG` settings in `.zshenv`.

Should be fixed by #20. We now try `defaults` first.
