### ISSUE TITLE
Switch to a Promise interface

### ISSUE THREAD

**Issue by albinekb** [sindresorhus/os-locale#20]
Hi!

What about releasing a 2.0 that returns a Promise instead of callbacks?
I'll send a PR if you'd accept that 👼 

Thanks ⭐

**Comment by SamVerschueren** [comment]
Definitely!  Go ahead :).

**Comment by nexdrew** [comment]
Agreed! It would be nice to maintain compatibility with Node 0.10 (purely because of downstream dependents), but I won't complain if we need to drop 0.10 and 0.12 with a major version bump.

**Comment by sindresorhus** [comment]
I think it's time to drop 0.10 and 0.12. I'm doing so in all my other modules. This module is stable anyway, so 1.x.x should continue to work fine.

**Comment by sindresorhus** [comment]
Fixed by #21.
