### ISSUE TITLE
[feature request] return system encoding

### ISSUE THREAD

**Issue by tommytroylin** [sindresorhus/os-locale#25]
In my project, I need to know the default encoding of OS.

If it is not difficult, would you please add a function that returns default encoding as well?

![image](https://cloud.githubusercontent.com/assets/3364271/24699813/d5ff39d0-1a27-11e7-9f07-abc892f7e4e5.png)

**Comment by sindresorhus** [comment]
You mean you want to ignore the `LANG` environment variable? Why? You should really follow what the user specifies.

**Comment by tommytroylin** [comment]
@sindresorhus 
No. I just need to display that encoding in some output.

I mean this
```javascript
// usage now
osLocale().then(locale => {
	console.log(locale);
	//=> 'en_US'
});

// new feature like this
osLocale().encoding().then(encoding => {
	console.log(encoding);
	//=> 'UTF-8'
});
```

**Comment by sindresorhus** [comment]
Ah, I misread your issue. I don't really see the point of that. You should just always use `UTF-8`.
