### ISSUE TITLE
add oslocale.sync()

### ISSUE THREAD

**Issue by bcoe** [sindresorhus/os-locale#3]
For synchronous tools like yargs, it would be awesome to have a synchronous mode for locale lookups.

**Comment by kevva** [comment]
:-1: for me, I'm generally against using synchronous stuff and in most cases you should be able to use the async method.

**Comment by sindresorhus** [comment]
@kevva I would almost always agree, but @bcoe need it for `yargs` which is sync (doesn't matter for CLI tools), so I don't see why not.

**Comment by kevva** [comment]
Alright, let's do it then :).
