### ISSUE TITLE
Use dash instead of underscore to be standard compliant

### ISSUE THREAD

**Issue by balupton** [sindresorhus/os-locale#30]
- https://tools.ietf.org/html/rfc5646
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_identification_and_negotiation
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by sindresorhus** [comment]
It's not worth doing a major version just for this, but I'll do it next year when I can target Node.js, which makes it worth doing a major version.

**Comment by MarkTiedemann** [comment]
Windows locales use dash instead of underscore, too (see [#35](https://github.com/sindresorhus/os-locale/issues/35)). Might be worth it to upgrade now.
