### ISSUE TITLE
Release v2.1.1 with mem 4.0.0

### ISSUE THREAD

**Issue by Runrioter** [sindresorhus/os-locale#32]
Hi @sindresorhus 

Currently, `mem` (< 4.0.0 versions) is vulnerable to Denial of Service (DoS) attacks. 
Can you release v2.1.1 with mem 4.0.0 ? 
There are many packages which depend on v2.

Thank you.

**Comment by sindresorhus** [comment]
That's not possible. `mem@3` requires Node.js 6 and only `os-locale@3` requires Node.js 6, so we can't upgrade to `mem@3` in `os-locale@2`.
