### ISSUE TITLE
yarn test causing "Error while loading rule '@typescript-eslint/await-thenable'"

### ISSUE THREAD

**Issue by joltmode** [sindresorhus/os-locale#44]
I wanted to contribute, but:
- fork
- clone
- `yarn install`
- `yarn test`

Results in an error:
![image](https://user-images.githubusercontent.com/1030080/78123606-14304900-7417-11ea-921c-93f55ab1a662.png)

Going through `test` commands individually, it's the `xo` binary that throws this.

**Comment by sindresorhus** [comment]
See https://github.com/xojs/xo/issues/450. I haven't had a chance to look into that yet. I'm currently travelling.
