### ISSUE TITLE
Callback not invoked on Windows XP

### ISSUE THREAD

**Issue by martinvl** [sindresorhus/os-locale#5]
The callback is never invoked when running on Windows XP. It seems the `wmic` process remains alive indefinitely, so the callback is invoked only if you kill the `wmic` process manually.

It turns out that running `wmic` from node works if you use one of the synchronous members of the `child_process` family. Why `wmic` won't exit when using one of the asynchronous `exec` variants is a mystery to me.

**Comment by kevva** [comment]
Haven't tested on XP but in Windows 7 it works fine.

**Comment by martinvl** [comment]
Yeah, this is specific to XP.

I'm not sure there is a nice way to fix this, but using #3 would be an acceptable workaround.

**Comment by kevva** [comment]
https://github.com/sindresorhus/os-locale/pull/4

**Comment by sindresorhus** [comment]
I don't really care about Windows XP.
