### ISSUE TITLE
Get error message: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module while import os-locale

### ISSUE THREAD

**Issue by LjjStar** [sindresorhus/os-locale#51]
Does anyone encounter the below issue while using the packag os-locale?

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Admin\Desktop\node_modules\os-locale\index.js
require() of ES modules is not supported.
require() of C:\Users\Admin\Desktop\node_modules\os-locale\index.js from C:\Users\Admin\Desktop\xxxx\lib\helper\utils.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\Admin\Desktop\node_modules\os-local

**Comment by LjjStar** [comment]
Does anyone encounter the below issue while using the packag os-locale?


Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Admin\Desktop\node_modules\os-locale\index.js
require() of ES modules is not supported.
require() of C:\Users\Admin\Desktop\node_modules\os-locale\index.js from C:\Users\Admin\Desktop\xxxx\lib\helper\utils.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\Admin\Desktop\node_modules\os-loca

**Comment by sindresorhus** [comment]
The error says it all.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by LjjStar** [comment]
Hi, @sindresorhus 
Actually, I use import {osLocale} from 'os-locale'; to import the package, but I still got this error message.
That's why I post this ticket.
I try all the recommended method, but it will cause other error.

**Comment by sindresorhus** [comment]
This is not really the place to ask for ESM support. This package correctly implements ESM. Please ensure your project is fully ESM (just using import statements does not mean it's native ESM). The above links has a guide on how to make your project ESM.

**Comment by LjjStar** [comment]
Thank you for your reply. @sindresorhus 
I will try it in my project.
