### ISSUE TITLE
wmic os get locale command failing

### ISSUE THREAD

**Issue by bapti** [sindresorhus/os-locale#6]
Hi - I'm not sure if this is an issue with your library so sorry if I've made a mistake.

I use the library yargs and it's started regularly throwing in your library through this line which was added as part of `1.2.0` in the change linked below

https://github.com/sindresorhus/os-locale/commit/cf130b6e79b0daf5b38092eda0fcca91a48340ed#diff-168726dbe96b3ce427e7fedce31bb0bc

```
var stdout = execFileSync('wmic', ['os', 'get', 'locale'], {encoding: 'utf8'});
```

It gives the following error every other build or so`Error: Command failed: wmic os get locale`

Does anything spring to mind, I've not found a whole lot online as to what the problem might be.  If you'd be willing I'd be happy to make a pull request to make this call fault tolerant.

Thanks
Neil

**Comment by bapti** [comment]
@sindresorhus 

I'm going to close this just now - I believe it just to be an environment issue, sorry for wasting your time.

**Comment by fritx** [comment]
:+1: there is no `wmic` on my windows machine
