### ISSUE TITLE
frightening warnings being displayed when detecting locale

### ISSUE THREAD

**Issue by bcoe** [sindresorhus/os-locale#8]
I've turned off locale detection in yargs for the time being, due to this error message I'm seeing on node `0.10.x`:

```
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /Users/benjamincoe/bcoe/yargs/node_modules/spawn-sync/error.log for more details
```

Like we discussed in that other thread, I think a configuration option for turning off spawning would be an ideal solution -- this would help address performance issues that @kevinsawicki raised as well.

**Comment by sindresorhus** [comment]
> Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /Users/benjamincoe/bcoe/yargs/node_modules/spawn-sync/error.log for more details

This is coming from [`spawn-sync`](https://github.com/ForbesLindesay/spawn-sync) which is used by the `execFileSync` polyfill I use here to make sync exec work on Node 0.10.

> Like we discussed in that other thread, I think a configuration option for turning off spawning would be an ideal solution

Sure, `{spawn: false}` sgty?

**Comment by bcoe** [comment]
@sindresorhus that sounds great to me, seems like we could just encourage people to make sure LC_ALL is set in their environment to take advantage of translations -- and it would make the Atom people happy to not have yargs spawning.

**Comment by nexdrew** [comment]
Also see PR #11.

**Comment by sindresorhus** [comment]
Added you both to the repo and npm package, since `yargs` depens on this. To reduce the [bus-factor](https://en.wikipedia.org/wiki/Bus_factor).

**Comment by bcoe** [comment]
awesome, #11 more than addresses my concerns thanks \o/
